### ISSUE TITLE
Error when trying to enter data donation study CMS

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#538] opened 2024-01-08 12:59 UTC
I followed these steps on the Next platform (both dev and prod):
1) Go to projects
2) Click project data donation item

Expected: To enter the data donation study CMS
Instead: I get either a "504 Gateway Time-out" or "502 Bad Gateway" error

**Comment by emielvdveen** [comment] 2024-01-09 12:01
Duplicate of #541

**Closed by emielvdveen** 2024-01-09 12:01 UTC
Labels: bug
